[package]
name = "zonebuilder"
version = "0.1.0"
authors = ["Robin Lovelace <rob00x@gmail.com>"]
edition = "2018"

[dependencies]
geo = { version = "0.17.1", features=["use-serde"] }
geojson = "0.22.2"
serde_json = { version = "1.0.0" }
structopt = "0.3.21"
