[package]
name = "zonebuilder"
version = "0.1.0"
authors = ["Robin Lovelace <rob00x@gmail.com>"]
edition = "2018"

[dependencies]
geo = { version = "0.17.1", features=["use-serde"] }
geojson = { git = "https://github.com/georust/geojson", features=["geo-types"] }
serde_json = { version = "1.0.0" }
structopt = "0.3.21"
