[package]
name = "zonebuilder"
version = "0.1.0"
authors = ["Robin Lovelace <rob00x@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.17.1"


